(lang dune 3.20)

(name ocamlfmt_js)

(generate_opam_files false)

(source
 (github fizzyelt/ocamlfmt_js))

(authors "FizzyElt")

(maintainers "fizzyelt.dev@outlook.com")

(license LICENSE)

(package
 (name ocamlfmt_js)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  (ocaml
   (>= 5.3))
  (js_of_ocaml
   (>= 6.2))
  (ocamlformat
   (= 0.28.1))))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
